"""create_tags

Revision ID: f6e83b2189f1
Revises: 0001_initial
Create Date: 2025-11-17 11:49:02.681894
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6e83b2189f1"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "color", sa.String(length=7), server_default="#000000", nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_tags_org_name"),
    )
    op.create_index(
        op.f("ix_tags_organization_id"), "tags", ["organization_id"], unique=False
    )
    op.alter_column(
        "activities",
        "type",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("'comment'::character varying"),
    )
    op.create_index(
        op.f("ix_activities_deal_id"), "activities", ["deal_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_organization_id"),
        "contacts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contacts_owner_id"), "contacts", ["owner_id"], unique=False
    )
    op.alter_column(
        "deals",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "deals",
        "currency",
        existing_type=sa.VARCHAR(length=8),
        nullable=False,
        existing_server_default=sa.text("'USD'::character varying"),
    )
    op.alter_column(
        "deals",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'new'::character varying"),
    )
    op.alter_column(
        "deals",
        "stage",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("'qualification'::character varying"),
    )
    op.create_index(op.f("ix_deals_contact_id"), "deals", ["contact_id"], unique=False)
    op.create_index(
        op.f("ix_deals_organization_id"), "deals", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_deals_owner_id"), "deals", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_organization_members_organization_id"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_members_user_id"),
        "organization_members",
        ["user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_tasks_deal_id"), "tasks", ["deal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_deal_id"), table_name="tasks")
    op.drop_index(
        op.f("ix_organization_members_user_id"), table_name="organization_members"
    )
    op.drop_index(
        op.f("ix_organization_members_organization_id"),
        table_name="organization_members",
    )
    op.drop_index(op.f("ix_deals_owner_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_organization_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_contact_id"), table_name="deals")
    op.alter_column(
        "deals",
        "stage",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
        existing_server_default=sa.text("'qualification'::character varying"),
    )
    op.alter_column(
        "deals",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'new'::character varying"),
    )
    op.alter_column(
        "deals",
        "currency",
        existing_type=sa.VARCHAR(length=8),
        nullable=True,
        existing_server_default=sa.text("'USD'::character varying"),
    )
    op.alter_column(
        "deals",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.drop_index(op.f("ix_contacts_owner_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_organization_id"), table_name="contacts")
    op.drop_index(op.f("ix_activities_deal_id"), table_name="activities")
    op.alter_column(
        "activities",
        "type",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
        existing_server_default=sa.text("'comment'::character varying"),
    )
    op.drop_index(op.f("ix_tags_organization_id"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
